---
title: "Childhood Obesity in CR"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(sf)
library(leaflet)
library(patchwork)
#library(mgcv)
library(spdep)
#library(visreg)
#library(DT)
library(INLA)

# setwd("C:/Users/manja/OneDrive - Universidad Estatal a Distancia/Escritorio/UCR/Maestria/KAUST/proyectoR")

```

```{r include=FALSE}
load("C:\\Users\\manja\\OneDrive - Universidad Estatal a Distancia\\Escritorio\\UCR\\Maestria\\KAUST\\data\\censusdb.R")

f1 <- "C:\\Users\\manja\\OneDrive - Universidad Estatal a Distancia\\Escritorio\\UCR\\Maestria\\KAUST\\data\\Map_cen_codes.csv"
Mapcencodes <- read.csv(f1,stringsAsFactors = FALSE) %>%
  mutate(CODIGO = as.character(CODIGO))
f2 <- "C:\\Users\\manja\\OneDrive - Universidad Estatal a Distancia\\Escritorio\\UCR\\Maestria\\KAUST\\data\\vars_dist.csv"
Vardist <- read.csv(f2,stringsAsFactors = FALSE) %>%
  mutate(CODIGO = as.character(CODIGO))

```

# Descriptive Analysis

## BMI by Age

```{r echo=FALSE}
ggplot(censusdb,aes(x = as.factor(EDADAÑOS), y = IMC)) + 
  geom_boxplot(width = 0.5,
               fill = "#35B779FF") +
    labs(x = "",
         y = "BMI") +
  theme_bw()

```

## Sample Composition

```{r echo=FALSE}
sexdf <- censusdb %>% 
  select(Sexo) %>%
  count(Sexo) %>%
  mutate(proportion = n/sum(n))

p1 <- sexdf %>%
  ggplot(aes(x = Sexo,
             y = proportion)) +
  geom_bar(stat = "identity",
           width = 0.2,
           fill = "#35B779FF") +
  ggtitle("Sex") +
  labs(x = "",
       y = "") +
  scale_y_continuous(labels = scales::percent) +
  theme_bw()

```


```{r echo=FALSE}
insttypedf <- censusdb %>% 
  select(TipoInstitucion) %>%
  count(TipoInstitucion) %>%
  mutate(proportion = n/sum(n))

p2 <- insttypedf %>%
  ggplot(aes(x = reorder(TipoInstitucion,proportion),
             y = proportion)) +
  geom_bar(stat = "identity",
           width = 0.2,
           fill = "#35B779FF") +
  coord_flip() +
  ggtitle("Institution Type") +
  labs(x = "",
       y = "") +
  scale_y_continuous(labels = scales::percent) +
  theme_bw()

```


```{r echo=FALSE}
provincedf <- censusdb %>% 
  select(Provincia) %>%
  count(Provincia) %>%
  mutate(proportion = n/sum(n))

p3 <- provincedf %>%
  ggplot(aes(x = reorder(Provincia,proportion),
             y = proportion)) +
  geom_bar(stat = "identity",
           width = 0.2,
           fill = "#35B779FF") +
  coord_flip() +
  ggtitle("Province") +
  labs(x = "",
       y = "") +
  scale_y_continuous(labels = scales::percent) +
  theme_bw()

```


```{r echo=FALSE}
agedf <- censusdb %>% 
  select(EDADAÑOS) %>%
  count(EDADAÑOS) %>%
  mutate(proportion = n/sum(n))

p4 <- agedf %>%
  ggplot(aes(x = EDADAÑOS,
             y = proportion)) +
  geom_bar(stat = "identity",
           width = 0.2,
           fill = "#35B779FF") +
  ggtitle("Age") +
  labs(x = "",
       y = "") +
  scale_y_continuous(labels = scales::percent) +
  theme_bw()

```


```{r echo=FALSE}
nutristatedf <- censusdb %>% 
  select(EstadoNutricional) %>%
  mutate(EstadoNutricional = as.factor(EstadoNutricional)) %>% 
  count(EstadoNutricional) %>%
  mutate(proportion = n/sum(n))

p5 <- nutristatedf %>%
  ggplot(aes(x = EstadoNutricional,
             y = proportion)) +
  geom_bar(stat = "identity",
           width = 0.2,
           fill = "#35B779FF") +
  ggtitle("Nutritional State") +
  labs(x = "",
       y = "") +
  scale_y_continuous(labels = scales::percent) +
  theme_bw()

```

```{r echo=FALSE}
p1 + p2
p3 + p4
p5
```

## Data by district

```{r include=FALSE}
owobdistrict <- censusdb %>%
  select(Provincia,Canton,Distrito,EstadoNutricional) %>%
  mutate(Canton = as.character(Canton),
         Distrito = as.character(Distrito)) %>% 
  group_by(Provincia,Canton,Distrito) %>% 
  count(EstadoNutricional,Distrito) %>%
  mutate(N = sum(n)) %>%
  filter(EstadoNutricional >= 4L) %>%
  pivot_wider(names_from = EstadoNutricional,
              values_from = n) %>%
  rename("nov"  = "4",
         "nob"  = "5") %>%
  mutate(n = sum(c(nov,nob),na.rm = TRUE)) %>% 
  group_by(Provincia,Canton,Distrito,N) %>% 
  #summarise(n = sum(n),.groups = "drop")
  mutate(Prev = n/N,
         Prevov = nov/N,
         Prevob = nob/N) %>%
  mutate(DIST_INDEX = paste0(Provincia,Canton,Distrito)) %>%
  left_join(Mapcencodes[,c("DIST_INDEX","CODIGO")],by = "DIST_INDEX")

```

## Maps
```{r include=FALSE}
f3 <- "C:\\Users\\manja\\OneDrive - Universidad Estatal a Distancia\\Escritorio\\UCR\\Maestria\\KAUST\\proyectoR\\39d23d7f-7660-426a-9597-2948bdaad6fd2020328-1-7atdtw.5qcln.shp"

CRdist <- st_read(f3)
# ggplot(data = CRdist) +
#   geom_sf()
box <- c(xmin = -86.5, ymin = 7.5, xmax = -82.5, ymax = 11.5)
#crbox <- st_bbox(box,crs = "WGS84")
CRdistc <- st_crop(CRdist,box)
CRdistc <- CRdistc %>%
  mutate(CODIGO = as.character(CODIGO),
         NOM_DIST = as.character(NOM_DIST))
  
CRdistc$NOM_CANT <- str_replace_all(CRdistc$NOM_CANT,c("AGUIRRE"="QUEPOS",
                                   "VALVERDE VEGA"="SARCHI"))

CRdistc <- CRdistc %>% left_join(owobdistrict[,c("CODIGO","Prev","N","n","nov","nob","Prevov","Prevob")],
                                 by = "CODIGO") %>%
  left_join(Vardist[,c(1,6:19)],by = "CODIGO")
CRdistc <- sf::st_cast(CRdistc,"MULTIPOLYGON")
CRdistdf <- st_drop_geometry(CRdistc)
```

## Covariates

```{r echo=FALSE, warning=FALSE}
CRdata <- CRdistdf %>%
  select(Prev,Prevov,Prevob,FUERA_TRABAJO:ACUEDUCTO) %>%
  pivot_longer(!c(Prev,Prevov,Prevob), 
               names_to = "var", 
               values_to = "value")

#Change colnames

# ggplot(CRdata,aes(x = value)) +
#   geom_histogram() +
#   facet_wrap(~ var, scales = "free") +
#   theme_bw()

ggplot(CRdata,aes(x = value, y = Prev)) +
  geom_point() +
  geom_smooth(method = "gam") +
  facet_wrap(~ var, scales = "free") +
  theme_bw() +
  ggtitle("Combined")

ggplot(CRdata,aes(x = value, y = Prevov)) +
  geom_point() +
  geom_smooth(method = "gam") +
  facet_wrap(~ var, scales = "free") +
  theme_bw() +
  ggtitle("Overweight")

ggplot(CRdata,aes(x = value, y = Prevob)) +
  geom_point() +
  geom_smooth(method = "gam") +
  facet_wrap(~ var, scales = "free") +
  theme_bw() +
  ggtitle("Obesity")

```

# Model

```{r include=FALSE}
crm <- CRdistc %>%
  #na.omit() %>% 
  mutate(ID = factor(ID))
crm$pid <- factor(1:nrow(crm))
crv <- CRdistdf %>% 
  #na.omit() %>% 
  mutate(ID = factor(ID))
crv$pid <- factor(1:nrow(crv))
# crm <- as(crm,Class = "Spatial")
#Acá se obtienen primero los vecinos espaciales para
#determinar cuáles no tienen vecinos (islas)
nb <- spdep::poly2nb(crm,
                    queen = TRUE)
iv <- which(sapply(nb,FUN = function(x) sum(x) == 0))
# Esto es para no eliminar a la isla Chira, que es un distrito insular
iv <- iv[-79]

#Bases finales para los modelos
crm <-  crm %>% slice(-c(iv))
crm <- as(crm,Class = "Spatial")
#plot(crm)
crv <- crv %>% slice(-c(iv))

#Vecinos por locación

nb <- spdep::poly2nb(crm,
                    queen = FALSE,
                    row.names = crm$pid)
names(nb) <- attr(nb,"region.id")

# nbs<-knearneigh(coordinates(crm), k = 3, longlat = T) #k=5 nearest neighbors
# nb<-knn2nb(nbs, row.names = crv$pid, sym = T)
# names(nb) <- attr(nb,"region.id")
# coords <- coordinates(crm)
# plot(crm);plot(nb, coords, add=TRUE)

# all.equal(sort(names(nb)),sort(levels(crm$ID)))
# all(names(nb) %in% levels(crm$INDEX))

#Vecinos por clusters
# gq <- nrow(crv)
# X <- sapply(1:gq, FUN = function(i){
#   crv[,26] == crv[i,26]
# })
# X <- X * 1
# diag(X) <- 0
# ids <- crv$ID
# M <- mat2listw(X,row.names = ids)
# nb <- M$neighbours
# names(nb) <- attr(nb,"region.id")


#Vecinos por clusters y por locación
# gq <- nrow(crv) 
# X <- sapply(1:gq, FUN = function(i){
#   crv[,26] == crv[i,26]
# })
# X <- X * 1
# diag(X) <- 0
# nb1 <- spdep::poly2nb(crm,
#                     queen = TRUE)
# Y <- nb2mat(nb1, style="B",zero.policy = TRUE)
# Z <- X * Y
# 
# ids <- crv$ID 
# M <- mat2listw(Z,row.names = ids)
# nb <- M$neighbours
# names(nb) <- attr(nb,"region.id")


```

### Condition Prevalence
```{r echo=FALSE, warning=FALSE}
mypalette <- colorNumeric( palette="viridis", domain=crm$Prev, na.color="transparent")
mytext <- paste(
    "Canton: ",crm$NOM_CANT,"<br/>",
    "District: ",crm$NOM_DIST,"<br/>",
    "Value: ", round(crm$Prev,2), "<br/>",
    "n: ", crm$n, "<br/>",
    "N: ", crm$N, "<br/>",
    sep="") %>%
  lapply(htmltools::HTML)

leaflet(crm) %>% 
  addTiles()  %>% 
  setView(lat=9.56, lng=-84.05 , zoom=7) %>%
  addProviderTiles("Esri.WorldGrayCanvas") %>% 
  addPolygons( fillColor = ~mypalette(crm[["Prev"]]), stroke=FALSE,fillOpacity = 1,smoothFactor = 0,label = mytext)

```


```{r eval=FALSE, include=FALSE}
#Moran test
moran.test(crm$Prev, nb2listw(nb, style="B",zero.policy = TRUE),zero.policy = TRUE)

```

# Model (Combined)
```{r include=FALSE}
crv$ID2 <- 1:nrow(crv)
nb2INLA("map.adj", nb)
g <- inla.read.graph(filename = "map.adj")

# NY8.mat <- as(nb2mat(nb, style = "B",zero.policy = TRUE), "Matrix")
# ICARmatrix <- Diagonal(nrow(NY8.mat), apply(NY8.mat, 1, sum)) - NY8.mat
# Cmatrix <- Diagonal(nrow(crv), 1) -  ICARmatrix
# max(eigen(Cmatrix)$values)
# 
# 
# mmatrix <- model.matrix(n ~ POB_URBANA +
#             FUERA_TRABAJO +
#             CARENCIA +
#             POB_014 +
#             HOG_MUJER +
#             OCUPANTES +
#             ESCOLA + I(ESCOLA^2), crv)
# W <- as(nb2mat(nb, style = "W",zero.policy = TRUE), "Matrix")
# Q.beta = Diagonal(n = ncol(mmatrix), x = 0.001)
# rho.min<- -1
# rho.max<- 1
# args.slm = list(
#    rho.min = rho.min ,
#    rho.max = rho.max,
#    W = W,
#    X = mmatrix,
#    Q.beta = Q.beta
# )
# hyper.slm = list(
#    prec = list(
#       prior = "loggamma", param = c(0.01, 0.01)),
#       rho = list(initial=0, prior = "logitbeta", param = c(1,1))
# )



# fr <- n ~ FUERA_TRABAJO +
#             CARENCIA +
#             POB_014 +
#             ESCOLA + I(ESCOLA^2) +
#   f(ID2, model = "bym2", graph = g)
# 
# fr <- n ~   POB_URBANA +
#             FUERA_TRABAJO +
#             CARENCIA +
#             POB_014 +
#             HOG_MUJER +
#             OCUPANTES +
#             ESCOLA + I(ESCOLA^2) +
#   f(ID2, model = "generic1", Cmatrix = Cmatrix)
# 
# fr <- n ~ -1 +
#   f(ID2, model = "slm", args.slm = args.slm,
#     hyper = hyper.slm)

fr <- n ~ POB_URBANA +
            FUERA_TRABAJO +
            CARENCIA +
            POB_014 +
            HOG_MUJER +
            OCUPANTES +
            ESCOLA + I(ESCOLA^2) +
  f(ID2, model = "bym2", graph = g)

fit <- inla(fr,
             family = 'binomial',
             Ntrials = N,
             data = crv,
             control.family = list(link = 'logit'),
             control.predictor = list(link = 1,
                                      compute = TRUE),
             control.compute = list(dic = TRUE,
                                    cpo = TRUE,
                                    waic = TRUE,
                                    return.marginals.predictor = TRUE))

fit$waic$waic

```


```{r echo=FALSE}
summary(fit)
```


```{r include=FALSE}
#inla.set.control.fixed.default()[c("mean.intercept", "prec.intercept", "mean", "prec")]
ft <- fit$summary.fitted.values
est <- ft[,1]
li <- ft[,3]
ls <- ft[,5]
#marg <- fit6$marginals.fitted.values[[1]]
#1 - inla.pmarginal(q = 0.3, marginal = marg)
excl <- sapply(fit$marginals.fitted.values,
FUN = function(marg){1 - inla.pmarginal(q = 0.3, marginal = marg)})
excm <- sapply(fit$marginals.fitted.values,
FUN = function(marg){1 - inla.pmarginal(q = 0.34, marginal = marg)})
excu <- sapply(fit$marginals.fitted.values,
FUN = function(marg){1 - inla.pmarginal(q = 0.38, marginal = marg)})



geodf <- st_as_sf(crm)
mdata <- cbind(geodf,est = est,li = li,ls = ls,excl = excl,excm = excm, excu = excu)
```

### Fitted values (mean)
```{r echo=FALSE}
mypalette <- colorNumeric( palette="viridis", domain=c(0.125,0.56), na.color="transparent")
mytext <- paste(
    "Canton: ",mdata$NOM_CANT,"<br/>",
    "District: ",mdata$NOM_DIST,"<br/>",
    "Value: ", round(mdata$est,2), "<br/>",
    sep="") %>%
  lapply(htmltools::HTML)

leaflet(mdata) %>% 
  addTiles()  %>% 
  setView(lat=9.56, lng=-84.05 , zoom=7) %>%
  addProviderTiles("Esri.WorldGrayCanvas") %>% 
  addPolygons( fillColor = ~mypalette(mdata[["est"]]), stroke=FALSE,fillOpacity = 1,smoothFactor = 0,label = mytext)

```



### Exceedence probability (0.29 prevalence)
```{r echo=FALSE}
mypalette <- colorNumeric( palette="viridis", domain=c(0,1), na.color="transparent")
mytext <- paste(
    "Canton: ",mdata$NOM_CANT,"<br/>",
    "District: ",mdata$NOM_DIST,"<br/>",
    "Value: ", round(mdata$excl,2), "<br/>",
    sep="") %>%
  lapply(htmltools::HTML)

leaflet(mdata) %>% 
  addTiles()  %>% 
  setView(lat=9.56, lng=-84.05 , zoom=7) %>%
  addProviderTiles("Esri.WorldGrayCanvas") %>% 
  addPolygons( fillColor = ~mypalette(mdata[["excl"]]), stroke=FALSE,fillOpacity = 1,smoothFactor = 0,label = mytext)

```


### Exceedence probability (0.34 prevalence)
```{r echo=FALSE}
mypalette <- colorNumeric( palette="viridis", domain=c(0,1), na.color="transparent")
mytext <- paste(
    "Canton: ",mdata$NOM_CANT,"<br/>",
    "District: ",mdata$NOM_DIST,"<br/>",
    "Value: ", round(mdata$excm,2), "<br/>",
    sep="") %>%
  lapply(htmltools::HTML)

leaflet(mdata) %>% 
  addTiles()  %>% 
  setView(lat=9.56, lng=-84.05 , zoom=7) %>%
  addProviderTiles("Esri.WorldGrayCanvas") %>% 
  addPolygons( fillColor = ~mypalette(mdata[["excm"]]), stroke=FALSE,fillOpacity = 1,smoothFactor = 0,label = mytext)

```


### Exceedence probability (0.38 prevalence)
```{r echo=FALSE}
mypalette <- colorNumeric( palette="viridis", domain=c(0,1), na.color="transparent")
mytext <- paste(
    "Canton: ",mdata$NOM_CANT,"<br/>",
    "District: ",mdata$NOM_DIST,"<br/>",
    "Value: ", round(mdata$excu,2), "<br/>",
    sep="") %>%
  lapply(htmltools::HTML)

leaflet(mdata) %>% 
  addTiles()  %>% 
  setView(lat=9.56, lng=-84.05 , zoom=7) %>%
  addProviderTiles("Esri.WorldGrayCanvas") %>% 
  addPolygons( fillColor = ~mypalette(mdata[["excu"]]), stroke=FALSE,fillOpacity = 1,smoothFactor = 0,label = mytext)

```
