---
title: "Overweight Prevalence"
---

```{r include=FALSE}
load("C:\\Users\\manja\\OneDrive - Universidad Estatal a Distancia\\Escritorio\\UCR\\Maestria\\KAUST\\test3\\mdataov.Rdata")
```

### Data
```{r echo=FALSE, warning=FALSE}
mypalette <- colorNumeric( palette="viridis", domain=mdataov$Prevov, na.color="transparent")
mytext <- paste(
    "Canton: ",mdataov$NOM_CANT,"<br/>",
    "District: ",mdataov$NOM_DIST,"<br/>",
    "Value: ", round(mdataov$Prevov,2), "<br/>",
    "n: ", mdataov$nov, "<br/>",
    "N: ", mdataov$N, "<br/>",
    sep="") %>%
  lapply(htmltools::HTML)

leaflet(mdataov) %>% 
  addTiles()  %>% 
  setView(lat=9.56, lng=-84.05 , zoom=7) %>%
  addProviderTiles("Esri.WorldGrayCanvas") %>% 
  addPolygons( fillColor = ~mypalette(crm[["Prevov"]]), stroke=FALSE,fillOpacity = 1,smoothFactor = 0,label = mytext)


```


### Fitted values (mean)
```{r echo=FALSE}
mypalette <- colorNumeric( palette="viridis", domain=c(0.06,0.34), na.color="transparent")
mytext <- paste(
    "Canton: ",mdataov$NOM_CANT,"<br/>",
    "District: ",mdataov$NOM_DIST,"<br/>",
    "Value: ", round(mdataov$est,2), "<br/>",
    sep="") %>%
  lapply(htmltools::HTML)

leaflet(mdataov) %>% 
  addTiles()  %>% 
  setView(lat=9.56, lng=-84.05 , zoom=7) %>%
  addProviderTiles("Esri.WorldGrayCanvas") %>% 
  addPolygons( fillColor = ~mypalette(mdataov[["est"]]), stroke=FALSE,fillOpacity = 1,smoothFactor = 0,label = mytext)

```



### Exceedence probability (Percentile 20 - 0.18 prevalence)
```{r echo=FALSE}
mypalette <- colorNumeric( palette="viridis", domain=c(0,1), na.color="transparent")
mytext <- paste(
    "Canton: ",mdataov$NOM_CANT,"<br/>",
    "District: ",mdataov$NOM_DIST,"<br/>",
    "Value: ", round(mdataov$excl,2), "<br/>",
    sep="") %>%
  lapply(htmltools::HTML)

leaflet(mdataov) %>% 
  addTiles()  %>% 
  setView(lat=9.56, lng=-84.05 , zoom=7) %>%
  addProviderTiles("Esri.WorldGrayCanvas") %>% 
  addPolygons( fillColor = ~mypalette(mdataov[["excl"]]), stroke=FALSE,fillOpacity = 1,smoothFactor = 0,label = mytext)

```


### Exceedence probability (Percentile 50 - 0.20 prevalence)
```{r echo=FALSE}
mypalette <- colorNumeric( palette="viridis", domain=c(0,1), na.color="transparent")
mytext <- paste(
    "Canton: ",mdataov$NOM_CANT,"<br/>",
    "District: ",mdataov$NOM_DIST,"<br/>",
    "Value: ", round(mdataov$excm,2), "<br/>",
    sep="") %>%
  lapply(htmltools::HTML)

leaflet(mdataov) %>% 
  addTiles()  %>% 
  setView(lat=9.56, lng=-84.05 , zoom=7) %>%
  addProviderTiles("Esri.WorldGrayCanvas") %>% 
  addPolygons( fillColor = ~mypalette(mdataov[["excm"]]), stroke=FALSE,fillOpacity = 1,smoothFactor = 0,label = mytext)

```


### Exceedence probability (Percentile 80 - 0.22 prevalence)
```{r echo=FALSE}
mypalette <- colorNumeric( palette="viridis", domain=c(0,1), na.color="transparent")
mytext <- paste(
    "Canton: ",mdataov$NOM_CANT,"<br/>",
    "District: ",mdataov$NOM_DIST,"<br/>",
    "Value: ", round(mdataov$excu,2), "<br/>",
    sep="") %>%
  lapply(htmltools::HTML)

leaflet(mdataov) %>% 
  addTiles()  %>% 
  setView(lat=9.56, lng=-84.05 , zoom=7) %>%
  addProviderTiles("Esri.WorldGrayCanvas") %>% 
  addPolygons( fillColor = ~mypalette(mdataov[["excu"]]), stroke=FALSE,fillOpacity = 1,smoothFactor = 0,label = mytext)

```

